def device_count() -> int: ...
def is_available() -> bool: ...
def release_cache() -> None: ...
def synchronize(device=...) -> None: ...

__all__ = ["device_count", "is_available", "release_cache", "synchronize"]
